title: Rishabh
sub_title: My thoughts on front-end web development and other stuff.
author: Rishabh Rao
url: http://rishabhsrao.github.io
image: http://rishabhsrao.github.io/apple-touch-icon-precomposed.png
markdown: redcarpet
analytics_id: UA-29339243-1
excerpt_separator: ""

social_media:
  twitter: rishabhsrao
  github: rishabhsrao
  facebook: rishabhsrao
  google_plus: rishabhsrao
