title: Rishabh&rsquo;s blog
description: Hi there, I&rsquo;m Rishabh. I&rsquo; a developer from Bangalore, India. I write, tweet and code about front-end web development. When I&rsquo;m away from my laptop, I like to enjoy the simple things in life &mdash; a stroll in the park, reading a book or looking at the night sky.
author: Rishabh Rao
url: http://rishabhsrao.github.io
markdown: redcarpet
pygments: true
analytics_id: UA-29339243-1
excerpt_separator: ""

social_media:
  twitter: rishabhsrao
  github: rishabhsrao
  facebook: rishabhsrao
  google_plus: rishabhsrao
