title: Rishabh
sub_title: My thoughts on web front-end engineering and other stuff.
author: Rishabh Rao
url: http://rishabhsrao.github.io
markdown: redcarpet
pygments: true
analytics_id: UA-29339243-1
excerpt_separator: ""

social_media:
  twitter: rishabhsrao
  github: rishabhsrao
  facebook: rishabhsrao
  google_plus: rishabhsrao
